language: go

go:
  - 1.6
  
branches:
  only:
    - master

env:
  - GOOS=darwin GOARCH=386
  - GOOS=linux GOARCH=386
  - GOOS=windows GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=linux GOARCH=amd64
  - GOOS=windows GOARCH=amd64
